### ISSUE TITLE
Mixed Precision Objectives

### ISSUE THREAD

**Issue by Awallace3** [shehan807/ParrLO#7]
# Objectives
- [ ] similar to report figure 8, need to compare...:
    - [ ] same convergence (1e-4, 1e-6, 1e-7)
    - [ ] number of iterations to convergence
    - does convergence criteria have number same iterations?
    - Also normalize Wall Clock Time based on number of iterations to get time
      per iteration for single and double
    - Compare speedup compared to single precision speedup over double (reported 1.92)
- [ ] Recreate Fig. 1 from report with Schulz using single, double, and mixed precision:
    - expect single/multi to lower Schulz by less than half
# Tasks
- [ ] Better single vs. double precision study
- [ ] NERSC recreate environment
- [ ] Mixed precision algorithms:
    - [ ] Precondition?
    - [ ] Convergence switch?
- [ ] DCRD approach with Schulz to avoid A matrix replication costs
